-- MySQL Script generated by MySQL Workbench
-- Sun May 28 16:20:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `UserId` VARCHAR(45) NOT NULL,
  `PhoneNumber` INT UNSIGNED NULL,
  `PassWord` VARCHAR(45) NOT NULL,
  `UserName` VARCHAR(45) NULL,
  `RegistrationTime` DATE NULL,
  `LastLoginTime` DATE NULL,
  PRIMARY KEY (`UserId`, `PassWord`),
  UNIQUE INDEX `UserId_UNIQUE` (`UserId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `ISBN` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Author` VARCHAR(45) NULL,
  `Introduction` VARCHAR(45) NULL,
  PRIMARY KEY (`ISBN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventory` (
  `InventoryId` VARCHAR(45) NOT NULL,
  `ISBN` VARCHAR(45) NOT NULL,
  `StoreTime` DATE NULL,
  `Status` INT NULL,
  PRIMARY KEY (`InventoryId`, `ISBN`),
  UNIQUE INDEX `InventoryID_UNIQUE` (`InventoryId` ASC) VISIBLE,
  INDEX `ISBN_idx` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `ISBN`
    FOREIGN KEY (`ISBN`)
    REFERENCES `mydb`.`Book` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BorrowingRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BorrowingRecord` (
  `UserId` VARCHAR(45) NOT NULL,
  `InventoryId` VARCHAR(45) NOT NULL,
  `BorrowingTime` DATE NOT NULL,
  `ReturnTime` DATE NOT NULL,
  PRIMARY KEY (`UserId`, `InventoryId`, `BorrowingTime`, `ReturnTime`),
  INDEX `InventoryId_idx` (`InventoryId` ASC) VISIBLE,
  CONSTRAINT `UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `mydb`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `InventoryId`
    FOREIGN KEY (`InventoryId`)
    REFERENCES `mydb`.`Inventory` (`ISBN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
